version: '2.1'

executors:
  main:
    working_directory: ~/project/terraform-aws-shepherd
    docker:
      - image: cimg/base:2020.01
  python:
    working_directory: ~/project/terraform-aws-shepherd
    docker:
      - image: cimg/python:3.7

jobs:
  test:
    executor: main
    steps:
      - checkout
      - run:
          name: "Download and install terraform"
          command: |
            set -euo pipefail
            cd ~
            mkdir -p ~/bin
            curl -sSLO https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
            [ $(sha256sum terraform_${TERRAFORM_VERSION}_linux_amd64.zip | cut -f1 -d ' ') = ${TERRAFORM_SHA256SUM} ]
            unzip -o -d ~/bin -o terraform_${TERRAFORM_VERSION}_linux_amd64.zip
            rm -vf terraform_${TERRAFORM_VERSION}_linux_amd64.zip
          environment:
            TERRAFORM_VERSION: "0.13.5"
            TERRAFORM_SHA256SUM: "f7b7a7b1bfbf5d78151cfe3d1d463140b5fd6a354e71a7de2b5644e652ca5147"
      - run:
          name: "Download and install terraform-docs"
          command: |
            set -euo pipefail
            cd ~
            mkdir -p ~/bin
            curl -sSLO https://github.com/terraform-docs/terraform-docs/releases/download/v${TERRAFORM_DOCS_VERSION}/terraform-docs-v${TERRAFORM_DOCS_VERSION}-linux-amd64.tar.gz
            curl -sSLO https://github.com/terraform-docs/terraform-docs/releases/download/v${TERRAFORM_DOCS_VERSION}/terraform-docs-v${TERRAFORM_DOCS_VERSION}.sha256sum
            tar -xvzf terraform-docs-v${TERRAFORM_DOCS_VERSION}-linux-amd64.tar.gz
            [ $(sha256sum terraform-docs-v${TERRAFORM_DOCS_VERSION}-linux-amd64.tar.gz | cut -f1 -d' ') = $(grep linux-amd64 terraform-docs-v${TERRAFORM_DOCS_VERSION}.sha256sum | cut -f1 -d' ') ]
            chmod 755 terraform-docs
            mv terraform-docs ~/bin/terraform-docs
          environment:
            TERRAFORM_DOCS_VERSION: "0.14.1"
      - run: echo 'export PATH=~/bin:$PATH' >> $BASH_ENV
      - run: scripts/update-docs
      - run: scripts/format-files
      - run: git diff --exit-code
  test_python:
    executor: python
    steps:
      - checkout
      - run: pyenv install < ./.python-version
      - run: pip install black==20.8b1 flake8==3.8.4
      - run: black scripts/*.py
      - run: flake8 scripts/*.py

workflows:
  version: 2
  main:
    jobs:
      - test
      - test_python
